### PR TITLE
Konstanz: map lot names to legacy names, update geojson

### PR DESCRIPTION
**Pull request by hbruch**
This PR updates `konstanz` scraper and geojson, i.e. it maps parking name(s) legacy names

### CODE REVIEW

**Comment by defgsus** [comment]
Deleting `konstanz.geojson` and calling `python scraper.py write-geojson -p konstanz` fails in [konstanz.py line 91](https://github.com/ParkenDD/ParkAPI2-sources/pull/15/files#diff-1e1d3e2bec1a795c5888b7b10fd868830e807e239c4bc4a633401e03ea422da5R91)

It's probably a javascript habbit ;) should be `kwargs.update({`

**Comment by hbruch** [comment]
It's a python version issue. I'm using 3.9. Will change this. What is the oldest python version we should support? Perhaps we should document that e.g. in a setup.py?

**Comment by jklmnn** [comment]
The server that is currently running parkendd.de only has Python 3.9. However I wouldn't use that as a hard requirement since you will probably run it on something else. I suggest to use whatever you want to host it on as a requirement.

**Review by jklmnn — APPROVED** [review]

**Comment by hbruch** [comment]
write-geojson and scrape are still up-to-date

**Pull request merged**
